apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vote-isolate
  namespace: eva
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: eva
      app.kubernetes.io/name: example-voting-app-vote
  policyTypes:
    - Ingress
    - Egress