---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: voter
  labels:
        {{- include "example-voting-app.voter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
          {{- include "example-voting-app.voter.selectorLabels" . | nindent 6 }}
  template:
    spec:
      serviceAccountName: {{ include "example-voting-app.serviceAccountName" . }}
      containers:
      - name: voter
        image: {{ include "example-voting-app.voter.image" . }}
        env:
        - name: VOTE
          value: "vote"
        - name: PORT
          value: "80"
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 32Mi
    metadata:
      labels:
        {{- include "example-voting-app.voter.selectorLabels" . | nindent 8 }}
