{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "example-voting-app.fullname" . }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{- end -}}
