{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "example-voting-app.fullname" .}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "example-voting-app.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "example-voting-app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
