---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
        {{- include "example-voting-app.redis.labels" . | nindent 4 }}
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
        {{- include "example-voting-app.redis.selectorLabels" . | nindent 4 }}
