---
apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
        {{- include "example-voting-app.vote.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
        {{- include "example-voting-app.vote.selectorLabels" . | nindent 4 }}
