---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
        {{- include "example-voting-app.db.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
        {{- include "example-voting-app.db.selectorLabels" . | nindent 4 }}
