---
apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
        {{- include "example-voting-app.result.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
        {{- include "example-voting-app.result.selectorLabels" . | nindent 4 }}
